# Task status constants — 4 values per specs §3
TASK_STATUS_OPEN = "Open"
TASK_STATUS_IN_PROGRESS = "In Progress"
TASK_STATUS_BLOCKED = "Blocked"
TASK_STATUS_DONE = "Done"

TASK_STATUSES = (
    TASK_STATUS_OPEN,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_BLOCKED,
    TASK_STATUS_DONE,
)

# Linked entity type constants — 3 values
LINKED_ENTITY_TYPE_VOYAGE = "Voyage"
LINKED_ENTITY_TYPE_PORT_CALL = "PortCall"
LINKED_ENTITY_TYPE_VESSEL = "Vessel"

LINKED_ENTITY_TYPES = (
    LINKED_ENTITY_TYPE_VOYAGE,
    LINKED_ENTITY_TYPE_PORT_CALL,
    LINKED_ENTITY_TYPE_VESSEL,
)
