/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_admin_users__id__patch"];
        trace?: never;
    };
    "/api/v1/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vessels */
        get: operations["list_vessels_api_v1_vessels_get"];
        put?: never;
        /** Create Vessel */
        post: operations["create_vessel_api_v1_vessels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vessels/{vessel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vessel */
        get: operations["get_vessel_api_v1_vessels__vessel_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Vessel */
        patch: operations["update_vessel_api_v1_vessels__vessel_id__patch"];
        trace?: never;
    };
    "/api/v1/vessels/{vessel_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Vessel */
        post: operations["deactivate_vessel_api_v1_vessels__vessel_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ports */
        get: operations["list_ports_api_v1_ports_get"];
        put?: never;
        /** Create Port */
        post: operations["create_port_api_v1_ports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ports/{port_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port */
        get: operations["get_port_api_v1_ports__port_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Port */
        patch: operations["update_port_api_v1_ports__port_id__patch"];
        trace?: never;
    };
    "/api/v1/ports/{port_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Port */
        post: operations["deactivate_port_api_v1_ports__port_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/counterparties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Counterparties */
        get: operations["list_counterparties_api_v1_counterparties_get"];
        put?: never;
        /** Create Counterparty */
        post: operations["create_counterparty_api_v1_counterparties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/counterparties/{counterparty_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Counterparty */
        get: operations["get_counterparty_api_v1_counterparties__counterparty_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Counterparty */
        patch: operations["update_counterparty_api_v1_counterparties__counterparty_id__patch"];
        trace?: never;
    };
    "/api/v1/counterparties/{counterparty_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Counterparty */
        post: operations["deactivate_counterparty_api_v1_counterparties__counterparty_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/counterparties/{counterparty_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach Role */
        post: operations["attach_role_api_v1_counterparties__counterparty_id__roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/counterparties/{counterparty_id}/roles/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Detach Role */
        delete: operations["detach_role_api_v1_counterparties__counterparty_id__roles__role__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voyages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Voyages */
        get: operations["list_voyages_api_v1_voyages_get"];
        put?: never;
        /** Create Voyage */
        post: operations["create_voyage_api_v1_voyages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voyages/{voyage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Voyage */
        get: operations["get_voyage_api_v1_voyages__voyage_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Voyage */
        patch: operations["update_voyage_api_v1_voyages__voyage_id__patch"];
        trace?: never;
    };
    "/api/v1/voyages/{voyage_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Voyage Status */
        post: operations["transition_voyage_status_api_v1_voyages__voyage_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voyages/{voyage_id}/itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Itinerary Lines */
        get: operations["list_itinerary_lines_api_v1_voyages__voyage_id__itinerary_get"];
        put?: never;
        /** Insert Itinerary Line */
        post: operations["insert_itinerary_line_api_v1_voyages__voyage_id__itinerary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voyages/{voyage_id}/itinerary/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Itinerary Line */
        delete: operations["delete_itinerary_line_api_v1_voyages__voyage_id__itinerary__line_id__delete"];
        options?: never;
        head?: never;
        /** Update Itinerary Line */
        patch: operations["update_itinerary_line_api_v1_voyages__voyage_id__itinerary__line_id__patch"];
        trace?: never;
    };
    "/api/v1/voyages/{voyage_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_v1_voyages__voyage_id__workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_api_v1_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/voyages/{voyage_id}/port-calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Port Calls */
        get: operations["list_port_calls_api_v1_voyages__voyage_id__port_calls_get"];
        put?: never;
        /** Create Port Call */
        post: operations["create_port_call_api_v1_voyages__voyage_id__port_calls_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/port-calls/{port_call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Port Call */
        get: operations["get_port_call_api_v1_port_calls__port_call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Port Call */
        patch: operations["update_port_call_api_v1_port_calls__port_call_id__patch"];
        trace?: never;
    };
    "/api/v1/port-calls/{port_call_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Port Call */
        post: operations["transition_port_call_api_v1_port_calls__port_call_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/port-calls/{port_call_id}/agent-appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Appointments */
        get: operations["list_agent_appointments_api_v1_port_calls__port_call_id__agent_appointments_get"];
        put?: never;
        /** Nominate Agent */
        post: operations["nominate_agent_api_v1_port_calls__port_call_id__agent_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-appointments/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Agent Appointment */
        post: operations["cancel_agent_appointment_api_v1_agent_appointments__id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-appointments/{id}/appoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Appoint Agent */
        patch: operations["appoint_agent_api_v1_agent_appointments__id__appoint_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentAppointmentCreateDTO */
        AgentAppointmentCreateDTO: {
            /**
             * Agent Ref
             * Format: uuid
             */
            agent_ref: string;
            /**
             * Appointed Date
             * Format: date
             */
            appointed_date: string;
            /** Agent Appointment Ref */
            agent_appointment_ref?: string | null;
        };
        /** AgentAppointmentResponseDTO */
        AgentAppointmentResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Port Call Id
             * Format: uuid
             */
            port_call_id: string;
            /**
             * Agent Ref
             * Format: uuid
             */
            agent_ref: string;
            /**
             * Appointed Date
             * Format: date
             */
            appointed_date: string;
            /** Status */
            status: string;
            /** Agent Appointment Ref */
            agent_appointment_ref?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ContactDTO */
        ContactDTO: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Phone */
            phone: string;
            /** Role Hint */
            role_hint?: string | null;
        };
        /** CounterpartyCreateDTO */
        CounterpartyCreateDTO: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["ContactDTO"][];
        };
        /** CounterpartyResponseDTO */
        CounterpartyResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["ContactDTO"][];
            /**
             * Roles
             * @default []
             */
            roles: components["schemas"]["CounterpartyRoleResponseDTO"][];
        };
        /** CounterpartyRoleAttachDTO */
        CounterpartyRoleAttachDTO: {
            /** Role */
            role: string;
            /** Ports Serviced */
            ports_serviced?: string[] | null;
            /** Nomination Contact Email */
            nomination_contact_email?: string | null;
        };
        /** CounterpartyRoleResponseDTO */
        CounterpartyRoleResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Counterparty Id
             * Format: uuid
             */
            counterparty_id: string;
            /** Role */
            role: string;
            /** Ports Serviced */
            ports_serviced?: string[] | null;
            /** Nomination Contact Email */
            nomination_contact_email?: string | null;
        };
        /** CounterpartyUpdateDTO */
        CounterpartyUpdateDTO: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
            /** Contacts */
            contacts?: components["schemas"]["ContactDTO"][] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItineraryLineCreateDTO */
        ItineraryLineCreateDTO: {
            /**
             * Port Ref
             * Format: uuid
             */
            port_ref: string;
            /** Port Function */
            port_function: string;
            /**
             * Planned Eta
             * Format: date-time
             */
            planned_eta: string;
            /**
             * Planned Etd
             * Format: date-time
             */
            planned_etd: string;
            /** Sequence No */
            sequence_no?: number | null;
        };
        /** ItineraryLineResponseDTO */
        ItineraryLineResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Voyage Id
             * Format: uuid
             */
            voyage_id: string;
            /** Sequence No */
            sequence_no: number;
            /**
             * Port Ref
             * Format: uuid
             */
            port_ref: string;
            /** Port Function */
            port_function: string;
            /**
             * Planned Eta
             * Format: date-time
             */
            planned_eta: string;
            /**
             * Planned Etd
             * Format: date-time
             */
            planned_etd: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ItineraryLineUpdateDTO */
        ItineraryLineUpdateDTO: {
            /** Port Ref */
            port_ref?: string | null;
            /** Port Function */
            port_function?: string | null;
            /** Planned Eta */
            planned_eta?: string | null;
            /** Planned Etd */
            planned_etd?: string | null;
            /** Sequence No */
            sequence_no?: number | null;
        };
        /** LoginDTO */
        LoginDTO: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** PortCallCreateDTO */
        PortCallCreateDTO: {
            /**
             * Port Id
             * Format: uuid
             */
            port_id: string;
            /** Itinerary Line Id */
            itinerary_line_id?: string | null;
            /** Eta */
            eta?: string | null;
            /** Etd */
            etd?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
        };
        /** PortCallResponseDTO */
        PortCallResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Voyage Id
             * Format: uuid
             */
            voyage_id: string;
            /**
             * Port Id
             * Format: uuid
             */
            port_id: string;
            /** Itinerary Line Id */
            itinerary_line_id?: string | null;
            /** Status */
            status: string;
            /** Eta */
            eta?: string | null;
            /** Etd */
            etd?: string | null;
            /** Ata */
            ata?: string | null;
            /** Anchored Datetime */
            anchored_datetime?: string | null;
            /** Atb */
            atb?: string | null;
            /** Cargo Ops Started Datetime */
            cargo_ops_started_datetime?: string | null;
            /** Cargo Ops Completed Datetime */
            cargo_ops_completed_datetime?: string | null;
            /** Atd */
            atd?: string | null;
            /** Timezone Name */
            timezone_name: string;
            /** Timezone Offset Minutes */
            timezone_offset_minutes?: number | null;
            /** Nor Tendered Datetime */
            nor_tendered_datetime?: string | null;
            /** Nor Accepted Datetime */
            nor_accepted_datetime?: string | null;
            /** Free Pratique Granted */
            free_pratique_granted: boolean;
            /** Free Pratique Granted Datetime */
            free_pratique_granted_datetime?: string | null;
            /** Customs Cleared */
            customs_cleared: boolean;
            /** Customs Cleared Datetime */
            customs_cleared_datetime?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PortCallTransitionDTO */
        PortCallTransitionDTO: {
            /** To */
            to: string;
            /** At */
            at?: string | null;
        };
        /** PortCallUpdateDTO */
        PortCallUpdateDTO: {
            /** Status */
            status?: string | null;
            /** Eta */
            eta?: string | null;
            /** Etd */
            etd?: string | null;
            /** Ata */
            ata?: string | null;
            /** Anchored Datetime */
            anchored_datetime?: string | null;
            /** Atb */
            atb?: string | null;
            /** Cargo Ops Started Datetime */
            cargo_ops_started_datetime?: string | null;
            /** Cargo Ops Completed Datetime */
            cargo_ops_completed_datetime?: string | null;
            /** Atd */
            atd?: string | null;
            /** Nor Tendered Datetime */
            nor_tendered_datetime?: string | null;
            /** Nor Accepted Datetime */
            nor_accepted_datetime?: string | null;
            /** Free Pratique Granted */
            free_pratique_granted?: boolean | null;
            /** Free Pratique Granted Datetime */
            free_pratique_granted_datetime?: string | null;
            /** Customs Cleared */
            customs_cleared?: boolean | null;
            /** Customs Cleared Datetime */
            customs_cleared_datetime?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
            /** Correction Reason */
            correction_reason?: string | null;
        };
        /** PortCreateDTO */
        PortCreateDTO: {
            /** Unlocode */
            unlocode: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance Table Ref */
            distance_table_ref?: string | null;
        };
        /** PortResponseDTO */
        PortResponseDTO: {
            /** Unlocode */
            unlocode: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Distance Table Ref */
            distance_table_ref?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Country */
            country: string;
            /** Status */
            status: string;
        };
        /** PortSequenceItemDTO */
        PortSequenceItemDTO: {
            /** Port Code */
            port_code: string;
            /**
             * Planned Eta
             * Format: date-time
             */
            planned_eta: string;
            /**
             * Planned Etd
             * Format: date-time
             */
            planned_etd: string;
        };
        /** PortUpdateDTO */
        PortUpdateDTO: {
            /** Unlocode */
            unlocode?: string | null;
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Distance Table Ref */
            distance_table_ref?: string | null;
        };
        /** UserCreateDTO */
        UserCreateDTO: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Role Names */
            role_names: string[];
        };
        /** UserResponseDTO */
        UserResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Username */
            username: string;
            /** Is Active */
            is_active: boolean;
            /** Roles */
            roles: string[];
        };
        /** UserUpdateDTO */
        UserUpdateDTO: {
            /** Username */
            username?: string | null;
            /** Password */
            password?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VesselCreateDTO */
        VesselCreateDTO: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Imo */
            imo: string;
            /** Vessel Type */
            vessel_type: string;
            /** Flag */
            flag: string;
            /**
             * Active For Reporting
             * @default true
             */
            active_for_reporting: boolean;
        };
        /** VesselHeaderDTO */
        VesselHeaderDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** VesselResponseDTO */
        VesselResponseDTO: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Imo */
            imo: string;
            /** Vessel Type */
            vessel_type: string;
            /** Flag */
            flag: string;
            /**
             * Active For Reporting
             * @default true
             */
            active_for_reporting: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** VesselScheduleItemDTO */
        VesselScheduleItemDTO: {
            /**
             * Vessel Id
             * Format: uuid
             */
            vessel_id: string;
            /** Vessel Name */
            vessel_name: string;
            /** Voyages */
            voyages: components["schemas"]["VoyageBarDTO"][];
        };
        /** VesselScheduleResponse */
        VesselScheduleResponse: {
            /** Vessels */
            vessels: components["schemas"]["VesselScheduleItemDTO"][];
        };
        /** VesselUpdateDTO */
        VesselUpdateDTO: {
            /** Code */
            code?: string | null;
            /** Name */
            name?: string | null;
            /** Imo */
            imo?: string | null;
            /** Vessel Type */
            vessel_type?: string | null;
            /** Flag */
            flag?: string | null;
            /** Active For Reporting */
            active_for_reporting?: boolean | null;
        };
        /** VoyageBarDTO */
        VoyageBarDTO: {
            /**
             * Voyage Id
             * Format: uuid
             */
            voyage_id: string;
            /** Voyage No */
            voyage_no: string;
            /** Status */
            status: string;
            /**
             * Commencing Datetime
             * Format: date-time
             */
            commencing_datetime: string;
            /** Expected Completing Datetime */
            expected_completing_datetime?: string | null;
            /** Current Next Port Code */
            current_next_port_code?: string | null;
            /** Charterer */
            charterer?: string | null;
            /** Port Sequence */
            port_sequence: components["schemas"]["PortSequenceItemDTO"][];
        };
        /** VoyageCreateDTO */
        VoyageCreateDTO: {
            /** Voyage No */
            voyage_no: string;
            /**
             * Vessel Ref
             * Format: uuid
             */
            vessel_ref: string;
            /**
             * Commencing Datetime
             * Format: date-time
             */
            commencing_datetime: string;
            /** Charterer Ref */
            charterer_ref?: string | null;
            /** Previous Voyage Ref */
            previous_voyage_ref?: string | null;
            /** Voyage Instructions */
            voyage_instructions?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
            terms?: components["schemas"]["VoyageTermsDTO"] | null;
        };
        /** VoyageResponseDTO */
        VoyageResponseDTO: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Voyage No */
            voyage_no: string;
            /**
             * Vessel Ref
             * Format: uuid
             */
            vessel_ref: string;
            /** Charterer Ref */
            charterer_ref?: string | null;
            /** Status */
            status: string;
            /**
             * Commencing Datetime
             * Format: date-time
             */
            commencing_datetime: string;
            /** Expected Completing Datetime */
            expected_completing_datetime?: string | null;
            /** Expected Completing Manual Override */
            expected_completing_manual_override: boolean;
            /** Previous Voyage Ref */
            previous_voyage_ref?: string | null;
            /** Voyage Instructions */
            voyage_instructions?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
            /** Commenced At */
            commenced_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Closed At */
            closed_at?: string | null;
            /** Cancelled At */
            cancelled_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            terms?: components["schemas"]["VoyageTermsDTO"] | null;
            /** Itinerary Lines */
            itinerary_lines?: components["schemas"]["ItineraryLineResponseDTO"][];
        };
        /** VoyageStatusTransitionDTO */
        VoyageStatusTransitionDTO: {
            /** To */
            to: string;
        };
        /** VoyageTermsDTO */
        VoyageTermsDTO: {
            /** Charterer Name */
            charterer_name?: string | null;
            /** Cp Type */
            cp_type?: string | null;
            /** Cp Date */
            cp_date?: string | null;
            /** Cp Document Ref */
            cp_document_ref?: string | null;
        };
        /** VoyageUpdateDTO */
        VoyageUpdateDTO: {
            /** Voyage No */
            voyage_no?: string | null;
            /** Vessel Ref */
            vessel_ref?: string | null;
            /** Commencing Datetime */
            commencing_datetime?: string | null;
            /** Charterer Ref */
            charterer_ref?: string | null;
            /** Previous Voyage Ref */
            previous_voyage_ref?: string | null;
            /** Voyage Instructions */
            voyage_instructions?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
            /** Expected Completing Manual Override */
            expected_completing_manual_override?: boolean | null;
            /** Expected Completing Datetime */
            expected_completing_datetime?: string | null;
            terms?: components["schemas"]["VoyageTermsDTO"] | null;
        };
        /** VoyageWorkspaceResponse */
        VoyageWorkspaceResponse: {
            /**
             * Voyage Id
             * Format: uuid
             */
            voyage_id: string;
            /** Voyage No */
            voyage_no: string;
            /** Status */
            status: string;
            vessel: components["schemas"]["VesselHeaderDTO"];
            /** Charterer */
            charterer?: string | null;
            /** Cp Type */
            cp_type?: string | null;
            /** Cp Date */
            cp_date?: string | null;
            /** Cp Document Ref */
            cp_document_ref?: string | null;
            /**
             * Commencing Datetime
             * Format: date-time
             */
            commencing_datetime: string;
            /** Expected Completing Datetime */
            expected_completing_datetime?: string | null;
            /** Itinerary */
            itinerary: components["schemas"]["WorkspaceItineraryItemDTO"][];
            /** Voyage Instructions */
            voyage_instructions?: string | null;
            /** Ops Notes */
            ops_notes?: string | null;
        };
        /** WorkspaceItineraryItemDTO */
        WorkspaceItineraryItemDTO: {
            /** Sequence No */
            sequence_no: number;
            /** Port Code */
            port_code: string;
            /**
             * Planned Eta
             * Format: date-time
             */
            planned_eta: string;
            /**
             * Planned Etd
             * Format: date-time
             */
            planned_etd: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"][];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_admin_users__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vessels_api_v1_vessels_get: {
        parameters: {
            query?: {
                status?: string | null;
                vessel_type?: string | null;
                flag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vessel_api_v1_vessels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VesselCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vessel_api_v1_vessels__vessel_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vessel_api_v1_vessels__vessel_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VesselUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_vessel_api_v1_vessels__vessel_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ports_api_v1_ports_get: {
        parameters: {
            query?: {
                status?: string | null;
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_port_api_v1_ports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_port_api_v1_ports__port_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_port_api_v1_ports__port_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_port_api_v1_ports__port_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_counterparties_api_v1_counterparties_get: {
        parameters: {
            query?: {
                status?: string | null;
                role?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_counterparty_api_v1_counterparties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterpartyCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_counterparty_api_v1_counterparties__counterparty_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                counterparty_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_counterparty_api_v1_counterparties__counterparty_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                counterparty_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterpartyUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_counterparty_api_v1_counterparties__counterparty_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                counterparty_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attach_role_api_v1_counterparties__counterparty_id__roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                counterparty_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CounterpartyRoleAttachDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_role_api_v1_counterparties__counterparty_id__roles__role__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                counterparty_id: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterpartyResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voyages_api_v1_voyages_get: {
        parameters: {
            query?: {
                vessel_ref?: string | null;
                status?: string | null;
                charterer_ref?: string | null;
                commencing_start?: string | null;
                commencing_end?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoyageResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_voyage_api_v1_voyages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoyageCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoyageResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voyage_api_v1_voyages__voyage_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoyageResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_voyage_api_v1_voyages__voyage_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoyageUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoyageResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_voyage_status_api_v1_voyages__voyage_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoyageStatusTransitionDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoyageResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_itinerary_lines_api_v1_voyages__voyage_id__itinerary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryLineResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insert_itinerary_line_api_v1_voyages__voyage_id__itinerary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryLineCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryLineResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_itinerary_line_api_v1_voyages__voyage_id__itinerary__line_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_itinerary_line_api_v1_voyages__voyage_id__itinerary__line_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryLineUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryLineResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_v1_voyages__voyage_id__workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoyageWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_v1_schedule_get: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
                vessel_ids?: string[] | null;
                status?: string[] | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselScheduleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_port_calls_api_v1_voyages__voyage_id__port_calls_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCallResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_port_call_api_v1_voyages__voyage_id__port_calls_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voyage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortCallCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCallResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_port_call_api_v1_port_calls__port_call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCallResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_port_call_api_v1_port_calls__port_call_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortCallUpdateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCallResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_port_call_api_v1_port_calls__port_call_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortCallTransitionDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortCallResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_appointments_api_v1_port_calls__port_call_id__agent_appointments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAppointmentResponseDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nominate_agent_api_v1_port_calls__port_call_id__agent_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                port_call_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentAppointmentCreateDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAppointmentResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_agent_appointment_api_v1_agent_appointments__id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAppointmentResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    appoint_agent_api_v1_agent_appointments__id__appoint_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentAppointmentResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
