"""create_port_call_and_agent_appointment

Revision ID: 203ad034a5fa
Revises: 5e85a63811b4
Create Date: 2026-05-29 13:13:58.682366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = '203ad034a5fa'
down_revision: Union[str, Sequence[str], None] = '5e85a63811b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_calls',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('voyage_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('port_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('itinerary_line_id', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('eta', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('etd', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('ata', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('anchored_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('atb', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('cargo_ops_started_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('cargo_ops_completed_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('atd', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('timezone_name', sa.String(length=50), nullable=False),
    sa.Column('timezone_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('nor_tendered_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('nor_accepted_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('free_pratique_granted', sa.Boolean(), nullable=False),
    sa.Column('free_pratique_granted_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('customs_cleared', sa.Boolean(), nullable=False),
    sa.Column('customs_cleared_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('ops_notes', sa.String(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Planned', 'Arrived at Pilot Station', 'At Anchor', 'Berthed', 'Cargo Ops Completed', 'Departed')", name=op.f('ck_port_calls_check_port_call_status_enum')),
    sa.ForeignKeyConstraint(['itinerary_line_id'], ['itinerary_lines.id'], name=op.f('fk_port_calls_itinerary_line_id_itinerary_lines')),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], name=op.f('fk_port_calls_port_id_ports')),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], name=op.f('fk_port_calls_voyage_id_voyages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_calls'))
    )
    with op.batch_alter_table('port_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_calls_itinerary_line_id'), ['itinerary_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_calls_port_id'), ['port_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_calls_voyage_id'), ['voyage_id'], unique=False)

    op.create_table('agent_appointments',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('port_call_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('agent_ref', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('appointed_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agent_appointment_ref', sa.String(length=50), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Nominated', 'Appointed', 'Cancelled')", name=op.f('ck_agent_appointments_check_agent_appointment_status_enum')),
    sa.ForeignKeyConstraint(['agent_ref'], ['counterparties.id'], name=op.f('fk_agent_appointments_agent_ref_counterparties')),
    sa.ForeignKeyConstraint(['port_call_id'], ['port_calls.id'], name=op.f('fk_agent_appointments_port_call_id_port_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_appointments'))
    )
    with op.batch_alter_table('agent_appointments', schema=None) as batch_op:
        batch_op.create_index('ix_agent_appointment_active_unique', ['port_call_id'], unique=True, postgresql_where=sa.text("status != 'Cancelled'"), sqlite_where=sa.text("status != 'Cancelled'"))
        batch_op.create_index(batch_op.f('ix_agent_appointments_agent_ref'), ['agent_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_appointments_port_call_id'), ['port_call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_appointment_active_unique', postgresql_where=sa.text("status != 'Cancelled'"), sqlite_where=sa.text("status != 'Cancelled'"))
        batch_op.drop_index(batch_op.f('ix_agent_appointments_port_call_id'))
        batch_op.drop_index(batch_op.f('ix_agent_appointments_agent_ref'))

    op.drop_table('agent_appointments')
    with op.batch_alter_table('port_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_calls_voyage_id'))
        batch_op.drop_index(batch_op.f('ix_port_calls_port_id'))
        batch_op.drop_index(batch_op.f('ix_port_calls_itinerary_line_id'))

    op.drop_table('port_calls')
    # ### end Alembic commands ###
