"""create_voyage_and_itinerary

Revision ID: 229042b95756
Revises: 9a097737eb39
Create Date: 2026-05-28 11:48:55.784666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = '229042b95756'
down_revision: Union[str, Sequence[str], None] = '9a097737eb39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyages',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('voyage_no', sa.String(length=50), nullable=False),
    sa.Column('vessel_ref', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('charterer_ref', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
    sa.Column('previous_voyage_ref', advanced_alchemy.types.guid.GUID(length=16), nullable=True),
    sa.Column('terms_charterer_name', sa.String(length=255), nullable=True),
    sa.Column('terms_cp_type', sa.String(length=10), nullable=True),
    sa.Column('terms_cp_date', sa.Date(), nullable=True),
    sa.Column('terms_cp_document_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('commencing_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('expected_completing_datetime', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('expected_completing_manual_override', sa.Boolean(), nullable=False),
    sa.Column('voyage_instructions', sa.String(), nullable=True),
    sa.Column('ops_notes', sa.String(), nullable=True),
    sa.Column('commenced_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('completed_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('closed_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('cancelled_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Scheduled', 'Commenced', 'Completed', 'Closed', 'Cancelled')", name=op.f('ck_voyages_check_voyage_status_enum')),
    sa.CheckConstraint("terms_cp_type IN ('CVC', 'TC', 'VC')", name=op.f('ck_voyages_check_voyage_cp_type_enum')),
    sa.ForeignKeyConstraint(['charterer_ref'], ['counterparties.id'], name=op.f('fk_voyages_charterer_ref_counterparties')),
    sa.ForeignKeyConstraint(['previous_voyage_ref'], ['voyages.id'], name=op.f('fk_voyages_previous_voyage_ref_voyages')),
    sa.ForeignKeyConstraint(['vessel_ref'], ['vessels.id'], name=op.f('fk_voyages_vessel_ref_vessels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voyages'))
    )
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voyages_charterer_ref'), ['charterer_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_voyages_previous_voyage_ref'), ['previous_voyage_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_voyages_vessel_ref'), ['vessel_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_voyages_voyage_no'), ['voyage_no'], unique=True)

    op.create_table('itinerary_lines',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('voyage_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('port_ref', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('port_function', sa.String(length=20), nullable=False),
    sa.Column('planned_eta', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('planned_etd', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("port_function IN ('Load', 'Discharge', 'Bunker', 'Canal', 'Transit', 'Repairs', 'Other')", name=op.f('ck_itinerary_lines_check_port_function_enum')),
    sa.CheckConstraint('planned_etd >= planned_eta', name=op.f('ck_itinerary_lines_check_itinerary_line_eta_etd')),
    sa.ForeignKeyConstraint(['port_ref'], ['ports.id'], name=op.f('fk_itinerary_lines_port_ref_ports')),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], name=op.f('fk_itinerary_lines_voyage_id_voyages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_lines')),
    sa.UniqueConstraint('voyage_id', 'sequence_no', name='uq_voyage_sequence')
    )
    with op.batch_alter_table('itinerary_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_lines_port_ref'), ['port_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_itinerary_lines_voyage_id'), ['voyage_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_lines_voyage_id'))
        batch_op.drop_index(batch_op.f('ix_itinerary_lines_port_ref'))

    op.drop_table('itinerary_lines')
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voyages_voyage_no'))
        batch_op.drop_index(batch_op.f('ix_voyages_vessel_ref'))
        batch_op.drop_index(batch_op.f('ix_voyages_previous_voyage_ref'))
        batch_op.drop_index(batch_op.f('ix_voyages_charterer_ref'))

    op.drop_table('voyages')
    # ### end Alembic commands ###
