"""add_voyages_schedule_indexes

Revision ID: 5e85a63811b4
Revises: 5588a42e6d32
Create Date: 2026-05-29 01:31:46.079531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = '5e85a63811b4'
down_revision: Union[str, Sequence[str], None] = '5588a42e6d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.create_index('ix_voyages_status', ['status'], unique=False)
        batch_op.create_index('ix_voyages_vessel_window', ['vessel_ref', 'commencing_datetime', 'expected_completing_datetime'], unique=False)
        batch_op.create_index('ix_voyages_window', ['commencing_datetime', 'expected_completing_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voyages', schema=None) as batch_op:
        batch_op.drop_index('ix_voyages_window')
        batch_op.drop_index('ix_voyages_vessel_window')
        batch_op.drop_index('ix_voyages_status')
    # ### end Alembic commands ###
