"""add_ports_counterparties_roles

Revision ID: 9a097737eb39
Revises: d762925e18e5
Create Date: 2026-05-28 01:55:15.513229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = '9a097737eb39'
down_revision: Union[str, Sequence[str], None] = 'd762925e18e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counterparties',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contacts', sa.JSON(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Active', 'Inactive')", name=op.f('ck_counterparties_check_counterparty_status_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparties'))
    )
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparties_code'), ['code'], unique=True)

    op.create_table('ports',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('unlocode', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('distance_table_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('Active', 'Inactive')", name=op.f('ck_ports_check_port_status_enum')),
    sa.CheckConstraint('latitude BETWEEN -90.0 AND 90.0', name=op.f('ck_ports_check_port_latitude_range')),
    sa.CheckConstraint('length(unlocode) = 5', name=op.f('ck_ports_check_port_unlocode_length')),
    sa.CheckConstraint('longitude BETWEEN -180.0 AND 180.0', name=op.f('ck_ports_check_port_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ports'))
    )
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ports_unlocode'), ['unlocode'], unique=True)

    op.create_table('counterparty_roles',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('counterparty_id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('ports_serviced', sa.JSON(), nullable=True),
    sa.Column('nomination_contact_email', sa.String(length=255), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('Owner', 'Charterer', 'Agent', 'Supplier', 'TechnicalManager')", name=op.f('ck_counterparty_roles_check_counterparty_role_enum')),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], name=op.f('fk_counterparty_roles_counterparty_id_counterparties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparty_roles')),
    sa.UniqueConstraint('counterparty_id', 'role', name='uq_counterparty_role')
    )
    with op.batch_alter_table('counterparty_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparty_roles_counterparty_id'), ['counterparty_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('counterparty_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_roles_counterparty_id'))

    op.drop_table('counterparty_roles')
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ports_unlocode'))

    op.drop_table('ports')
    with op.batch_alter_table('counterparties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparties_code'))

    op.drop_table('counterparties')
    # ### end Alembic commands ###
