"""Initial migration

Revision ID: cc05e063b804
Revises: 
Create Date: 2026-05-28 00:05:33.958566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = 'cc05e063b804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessels',
    sa.Column('id', advanced_alchemy.types.guid.GUID(length=16), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('imo', sa.String(length=7), nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('active_for_reporting', sa.Boolean(), nullable=False),
    sa.Column('owner_ref', sa.String(length=255), nullable=True),
    sa.Column('technical_manager_ref', sa.String(length=255), nullable=True),
    sa.Column('ops_manager_user_id', sa.String(length=255), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vessels'))
    )
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vessels_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vessels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vessels_code'))

    op.drop_table('vessels')
    # ### end Alembic commands ###
