"""Add Vessel enums and constraints

Revision ID: d762925e18e5
Revises: cc05e063b804
Create Date: 2026-05-28 00:32:20.858717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy


# revision identifiers, used by Alembic.
revision: str = 'd762925e18e5'
down_revision: Union[str, Sequence[str], None] = 'cc05e063b804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('check_vessel_imo_length', 'vessels', "length(imo) = 7")
    op.create_check_constraint('check_vessel_type_enum', 'vessels', "vessel_type IN ('Tanker', 'Bulker', 'Container', 'Other')")
    op.create_check_constraint('check_vessel_status_enum', 'vessels', "status IN ('Active', 'Inactive')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_vessel_status_enum', 'vessels', type_='check')
    op.drop_constraint('check_vessel_type_enum', 'vessels', type_='check')
    op.drop_constraint('check_vessel_imo_length', 'vessels', type_='check')
    # ### end Alembic commands ###
