# Delay type constants — 12 values per specs §2
DELAY_TYPE_WEATHER = "Weather"
DELAY_TYPE_MECHANICAL = "Mechanical"
DELAY_TYPE_PORT_CONGESTION = "Port Congestion"
DELAY_TYPE_AWAITING_BERTH = "Awaiting Berth"
DELAY_TYPE_AWAITING_ORDERS = "Awaiting Orders"
DELAY_TYPE_CARGO_OPERATIONS = "Cargo Operations"
DELAY_TYPE_BUNKERING_DELAY = "Bunkering Delay"
DELAY_TYPE_STRIKE = "Strike"
DELAY_TYPE_DEVIATION = "Deviation"
DELAY_TYPE_PIRACY_SECURITY = "Piracy/Security"
DELAY_TYPE_QUARANTINE_DISEASE = "Quarantine/Disease"
DELAY_TYPE_OTHER = "Other"

DELAY_TYPES = (
    DELAY_TYPE_WEATHER,
    DELAY_TYPE_MECHANICAL,
    DELAY_TYPE_PORT_CONGESTION,
    DELAY_TYPE_AWAITING_BERTH,
    DELAY_TYPE_AWAITING_ORDERS,
    DELAY_TYPE_CARGO_OPERATIONS,
    DELAY_TYPE_BUNKERING_DELAY,
    DELAY_TYPE_STRIKE,
    DELAY_TYPE_DEVIATION,
    DELAY_TYPE_PIRACY_SECURITY,
    DELAY_TYPE_QUARANTINE_DISEASE,
    DELAY_TYPE_OTHER,
)

# Fault attribution constants — 5 values per specs §2
FAULT_ATTRIBUTION_VESSEL = "Vessel"
FAULT_ATTRIBUTION_CHARTERER = "Charterer"
FAULT_ATTRIBUTION_PORT = "Port"
FAULT_ATTRIBUTION_WEATHER = "Weather"
FAULT_ATTRIBUTION_FORCE_MAJEURE = "Force Majeure"

FAULT_ATTRIBUTIONS = (
    FAULT_ATTRIBUTION_VESSEL,
    FAULT_ATTRIBUTION_CHARTERER,
    FAULT_ATTRIBUTION_PORT,
    FAULT_ATTRIBUTION_WEATHER,
    FAULT_ATTRIBUTION_FORCE_MAJEURE,
)
