# Alert type constants — 10 values per specs §3
ALERT_TYPE_ETA_OVERDUE = "ETA Overdue"
ALERT_TYPE_DEPARTURE_OVERDUE = "Departure Overdue"
ALERT_TYPE_NOR_NOT_TENDERED = "NOR Not Tendered"
ALERT_TYPE_AGENT_NOT_CONFIRMED = "Agent Not Confirmed"
ALERT_TYPE_FORM_NOT_RECEIVED = "Form Not Received"
ALERT_TYPE_BUNKER_REQUEST_BLOCKED = "Bunker Request Blocked"
ALERT_TYPE_VOYAGE_NOT_COMMENCED = "Voyage Not Commenced"
ALERT_TYPE_PERFORMANCE_DEVIATION = "Performance Deviation"
ALERT_TYPE_CONSUMPTION_DEVIATION = "Consumption Deviation"
ALERT_TYPE_NOON_REPORT_MISSING = "Noon Report Missing"

ALERT_TYPES = (
    ALERT_TYPE_ETA_OVERDUE,
    ALERT_TYPE_DEPARTURE_OVERDUE,
    ALERT_TYPE_NOR_NOT_TENDERED,
    ALERT_TYPE_AGENT_NOT_CONFIRMED,
    ALERT_TYPE_FORM_NOT_RECEIVED,
    ALERT_TYPE_BUNKER_REQUEST_BLOCKED,
    ALERT_TYPE_VOYAGE_NOT_COMMENCED,
    ALERT_TYPE_PERFORMANCE_DEVIATION,
    ALERT_TYPE_CONSUMPTION_DEVIATION,
    ALERT_TYPE_NOON_REPORT_MISSING,
)

# Severity constants — 3 values
SEVERITY_INFO = "Info"
SEVERITY_WARNING = "Warning"
SEVERITY_CRITICAL = "Critical"

SEVERITIES = (
    SEVERITY_INFO,
    SEVERITY_WARNING,
    SEVERITY_CRITICAL,
)

# Linked entity type constants — 3 values
LINKED_ENTITY_TYPE_VOYAGE = "Voyage"
LINKED_ENTITY_TYPE_PORT_CALL = "PortCall"
LINKED_ENTITY_TYPE_VESSEL = "Vessel"

LINKED_ENTITY_TYPES = (
    LINKED_ENTITY_TYPE_VOYAGE,
    LINKED_ENTITY_TYPE_PORT_CALL,
    LINKED_ENTITY_TYPE_VESSEL,
)
