FUEL_TYPE_HFO = "HFO"
FUEL_TYPE_VLSFO = "VLSFO"
FUEL_TYPE_MGO = "MGO"
FUEL_TYPE_LSMGO = "LSMGO"
FUEL_TYPE_HSFO = "HSFO"
FUEL_TYPE_ULSD = "ULSD"
FUEL_TYPE_LNG = "LNG"
FUEL_TYPE_BIOFUEL = "Biofuel"

FUEL_TYPES = (
    FUEL_TYPE_HFO,
    FUEL_TYPE_VLSFO,
    FUEL_TYPE_MGO,
    FUEL_TYPE_LSMGO,
    FUEL_TYPE_HSFO,
    FUEL_TYPE_ULSD,
    FUEL_TYPE_LNG,
    FUEL_TYPE_BIOFUEL,
)

STATUS_RAISED = "Raised"
STATUS_IN_PROGRESS = "In Progress"
STATUS_STEMMED = "Stemmed"
STATUS_SUPPLIED = "Supplied"
STATUS_BLOCKED = "Blocked"

STATUSES = (
    STATUS_RAISED,
    STATUS_IN_PROGRESS,
    STATUS_STEMMED,
    STATUS_SUPPLIED,
    STATUS_BLOCKED,
)

# Legal FSM transitions: source → set of allowed targets
# D-ENTRY-1: unblock target is operator-supplied in transition body
LEGAL_TRANSITIONS: dict[str, tuple[str, ...]] = {
    STATUS_RAISED: (STATUS_IN_PROGRESS, STATUS_BLOCKED),
    STATUS_IN_PROGRESS: (STATUS_STEMMED, STATUS_BLOCKED),
    STATUS_STEMMED: (STATUS_SUPPLIED, STATUS_BLOCKED),
    STATUS_SUPPLIED: (),  # terminal — no outgoing transitions
    STATUS_BLOCKED: (STATUS_RAISED, STATUS_IN_PROGRESS, STATUS_STEMMED),
}
